# Site settings
title: Your awesome title
email: markallenhall@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Home site of Mark Allen Hall and Mankind Software.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mankindsoftware.github.io/mankind" # the base hostname & protocol for your site
twitter_username: 
github_username:  mankindsoftware

# Build settings
markdown: kramdown
